version: '3'

services:
  stock-chart:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '2468:2468'
    image: magshehu/stock-chart-and-database

  database:
    image: mongo:latest